services:
    web:
        build: .
        ports:
            - "8000:8000"
        develop:
            watch:
                - action: sync
                  path: .
                  target: /z-paint
                  ignore:
                      - package.json
                      - vite.config.ts

                - action: rebuild
                  path: package.json

                - action: sync+restart
                  path: ./vite.config.ts
                  target: /z-paint/vite.config.ts
